CREATE TABLE "users" (
  "id_user" int NOT NULL AUTO_INCREMENT,
  "username" varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL,
  "email" varchar(150) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL,
  "password_hash" varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL,
  "fullname" varchar(150) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL,
  "phone_number" varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  "id_role" int NOT NULL,
  "id_status_user" int NOT NULL,
  "failed_login_attempts" int NOT NULL DEFAULT '0',
  "locked_until" datetime DEFAULT NULL,
  "deleted_at" datetime DEFAULT NULL,
  "created_at" timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY ("id_user"),
  UNIQUE KEY "username" ("username"),
  UNIQUE KEY "email" ("email"),
  KEY "fk_users_role" ("id_role"),
  KEY "fk_users_status" ("id_status_user"),
  CONSTRAINT "fk_users_role" FOREIGN KEY ("id_role") REFERENCES "roles" ("id_role") ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT "fk_users_status" FOREIGN KEY ("id_status_user") REFERENCES "status_user" ("id_status_user") ON DELETE RESTRICT ON UPDATE RESTRICT
);
CREATE TABLE "status_user" (
  "id_status_user" int NOT NULL AUTO_INCREMENT,
  "status_name" varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL,
  "description" varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  "created_at" timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY ("id_status_user"),
  UNIQUE KEY "status_name" ("status_name")
);
CREATE TABLE "sim_types" (
  "id_sim_type" int NOT NULL AUTO_INCREMENT,
  "sim_type" varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL,
  "description" varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  "created_at" timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY ("id_sim_type"),
  UNIQUE KEY "sim_type" ("sim_type")
);
CREATE TABLE "sim_status" (
  "id_sim_status" int NOT NULL AUTO_INCREMENT,
  "sim_status" varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL,
  "description" varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  "created_at" timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY ("id_sim_status"),
  UNIQUE KEY "status_name" ("sim_status")
);
CREATE TABLE "sim_cards" (
  "id_sim" int NOT NULL AUTO_INCREMENT,
  "iccid" varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL,
  "imsi" varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL,
  "qr_code" text CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci,
  "activation_code" varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  "phone_number" varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  "id_sim_type" int DEFAULT NULL,
  "id_package" int DEFAULT NULL,
  "id_sim_status" int NOT NULL DEFAULT '1',
  "imported_by" int DEFAULT NULL,
  "id_file" int DEFAULT NULL,
  "imported_at" datetime DEFAULT NULL,
  "deleted_at" datetime DEFAULT NULL,
  "created_at" timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY ("id_sim"),
  UNIQUE KEY "iccid" ("iccid"),
  UNIQUE KEY "imsi" ("imsi"),
  KEY "fk_sim_type" ("id_sim_type"),
  KEY "fk_sim_status" ("id_sim_status"),
  KEY "fk_sim_imported_by" ("imported_by"),
  KEY "fk_sim_file" ("id_file"),
  KEY "idx_sim_cards_type_status" ("id_sim_type","id_sim_status"),
  KEY "fk_sim_package" ("id_package"),
  CONSTRAINT "fk_sim_file" FOREIGN KEY ("id_file") REFERENCES "history_sim_card_file" ("id_file") ON DELETE SET NULL ON UPDATE RESTRICT,
  CONSTRAINT "fk_sim_imported_by" FOREIGN KEY ("imported_by") REFERENCES "users" ("id_user") ON DELETE SET NULL ON UPDATE RESTRICT,
  CONSTRAINT "fk_sim_package" FOREIGN KEY ("id_package") REFERENCES "packages" ("id_package") ON DELETE SET NULL ON UPDATE RESTRICT,
  CONSTRAINT "fk_sim_status" FOREIGN KEY ("id_sim_status") REFERENCES "sim_status" ("id_sim_status") ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT "fk_sim_type" FOREIGN KEY ("id_sim_type") REFERENCES "sim_types" ("id_sim_type") ON DELETE SET NULL ON UPDATE RESTRICT
);
CREATE TABLE "roles" (
  "id_role" int NOT NULL AUTO_INCREMENT,
  "role_name" varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL,
  "description" varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  "created_at" timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY ("id_role"),
  UNIQUE KEY "role_name" ("role_name")
);
CREATE TABLE "registrations_status" (
  "id_registration_status" int NOT NULL AUTO_INCREMENT,
  "status_name" varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL,
  "description" varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  "created_at" timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY ("id_registration_status"),
  UNIQUE KEY "status_name" ("status_name")
);
CREATE TABLE "registrations" (
  "id_registration" int NOT NULL AUTO_INCREMENT,
  "id_registration_status" int NOT NULL DEFAULT '1',
  "id_customer" int NOT NULL,
  "id_sim" int NOT NULL,
  "id_agent" int NOT NULL,
  "registered_at" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "reviewed_by" int DEFAULT NULL,
  "reviewed_at" datetime DEFAULT NULL,
  "notes" varchar(1000) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  "created_at" timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  "deleted_at" datetime DEFAULT NULL,
  PRIMARY KEY ("id_registration"),
  KEY "fk_reg_status" ("id_registration_status"),
  KEY "fk_reg_customer" ("id_customer"),
  KEY "fk_reg_sim" ("id_sim"),
  KEY "fk_reg_agent" ("id_agent"),
  KEY "fk_reg_reviewer" ("reviewed_by"),
  KEY "idx_registrations_registered_at" ("registered_at"),
  KEY "idx_registrations_agent" ("id_agent"),
  KEY "idx_registrations_sim" ("id_sim"),
  CONSTRAINT "fk_reg_agent" FOREIGN KEY ("id_agent") REFERENCES "agents" ("id_agent") ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT "fk_reg_customer" FOREIGN KEY ("id_customer") REFERENCES "customers" ("id_customer") ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT "fk_reg_reviewer" FOREIGN KEY ("reviewed_by") REFERENCES "users" ("id_user") ON DELETE SET NULL ON UPDATE RESTRICT,
  CONSTRAINT "fk_reg_sim" FOREIGN KEY ("id_sim") REFERENCES "sim_cards" ("id_sim") ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT "fk_reg_status" FOREIGN KEY ("id_registration_status") REFERENCES "registrations_status" ("id_registration_status") ON DELETE RESTRICT ON UPDATE RESTRICT
);
CREATE TABLE "refresh_tokens" (
  "id_refresh_token" bigint NOT NULL AUTO_INCREMENT,
  "id_user" int NOT NULL,
  "token_hash" varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL,
  "issued_at" datetime DEFAULT CURRENT_TIMESTAMP,
  "expires_at" datetime NOT NULL,
  "last_activity_at" datetime DEFAULT NULL,
  "revoked" tinyint(1) NOT NULL DEFAULT '0',
  "ip_address" varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  "user_agent" text CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci,
  "device_name" varchar(150) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  PRIMARY KEY ("id_refresh_token"),
  UNIQUE KEY "token_hash" ("token_hash"),
  KEY "fk_refresh_user" ("id_user"),
  CONSTRAINT "fk_refresh_user" FOREIGN KEY ("id_user") REFERENCES "users" ("id_user") ON DELETE CASCADE ON UPDATE RESTRICT
);
CREATE TABLE "packages" (
  "id_package" int NOT NULL AUTO_INCREMENT,
  "package_name" varchar(100) NOT NULL,
  "package_type" varchar(50) NOT NULL DEFAULT 'Tourist',
  "sim_type" varchar(20) NOT NULL DEFAULT 'eSIM',
  "data_gb" decimal(10,2) NOT NULL,
  "validity_days" int NOT NULL,
  "price" decimal(12,2) DEFAULT '0.00',
  "description" varchar(500) DEFAULT NULL,
  "status" tinyint(1) NOT NULL DEFAULT '1',
  "created_at" timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY ("id_package")
);
CREATE TABLE "history_sim_card_file" (
  "id_file" int NOT NULL AUTO_INCREMENT,
  "file_name" varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL,
  "id_agent" int DEFAULT NULL,
  "uploaded_by" int DEFAULT NULL,
  "total_rows" int DEFAULT '0',
  "success_rows" int DEFAULT '0',
  "failed_rows" int DEFAULT '0',
  "created_at" timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY ("id_file"),
  KEY "fk_history_agent" ("id_agent"),
  KEY "fk_history_uploaded_by" ("uploaded_by"),
  CONSTRAINT "fk_history_agent" FOREIGN KEY ("id_agent") REFERENCES "agents" ("id_agent") ON DELETE SET NULL ON UPDATE RESTRICT,
  CONSTRAINT "fk_history_uploaded_by" FOREIGN KEY ("uploaded_by") REFERENCES "users" ("id_user") ON DELETE SET NULL ON UPDATE RESTRICT
);
CREATE TABLE "customers" (
  "id_customer" int NOT NULL AUTO_INCREMENT,
  "first_name" varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL,
  "last_name" varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL,
  "passport_number" varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL,
  "nationality" varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  "date_of_birth" date DEFAULT NULL,
  "passport_expiry_date" date DEFAULT NULL,
  "phone_number" varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  "passport_photo" varchar(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  "created_at" timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY ("id_customer"),
  UNIQUE KEY "passport_number" ("passport_number")
);
CREATE TABLE "audit_logs" (
  "id_audit_log" bigint NOT NULL AUTO_INCREMENT,
  "id_user" int DEFAULT NULL,
  "action" varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL,
  "target_entity" varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  "target_id" varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  "metadata" json DEFAULT NULL,
  "ip_address" varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  "user_agent" text CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci,
  "created_at" timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  "old_value" text CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci,
  PRIMARY KEY ("id_audit_log"),
  KEY "fk_audit_user" ("id_user"),
  CONSTRAINT "fk_audit_user" FOREIGN KEY ("id_user") REFERENCES "users" ("id_user") ON DELETE SET NULL ON UPDATE RESTRICT
);
CREATE TABLE "agents" (
  "id_agent" int NOT NULL AUTO_INCREMENT,
  "agent_name" varchar(150) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL,
  "contact_phone" varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  "contact_email" varchar(150) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  "address" varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  "public_token" varchar(64) NOT NULL,
  "created_by" int DEFAULT NULL,
  "deleted_at" datetime DEFAULT NULL,
  "created_at" timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY ("id_agent"),
  UNIQUE KEY "uk_agents_public_token" ("public_token"),
  KEY "fk_agents_created_by" ("created_by"),
  CONSTRAINT "fk_agents_created_by" FOREIGN KEY ("created_by") REFERENCES "users" ("id_user") ON DELETE SET NULL ON UPDATE RESTRICT
);
